### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by ghost** [L0ngxhn/hackintosh-GIGABYTE-Z390-GAMING-X#2]
购买usb一分二的线，网卡是bcm94360cd，请问下把购买的usb一分二的线是插在哪里的？
网上解决方法是：安装到USB3.0上就完全正常了，需要买一根3.0转2.0的线，楼主也是这样解决的么

**Comment by yexingzhi** [comment]
我的网卡不是这个型号，我也不太清楚

李云飞 <notifications@github.com> 于2020年12月7日周一 下午5:23写道：

**Comment by L0ngxhn** [comment]
> 购买usb一分二的线，网卡是bcm94360cd，请问下把购买的usb一分二的线是插在哪里的？
> 网上解决方法是：安装到USB3.0上就完全正常了，需要买一根3.0转2.0的线，楼主也是这样解决的么

不好意思，最近比较忙。 是的，我也在某宝买了一根1分2的线。不过我是usb2 to 2 的。目前正常睡眠。曾经有段时间的EFI会直接睡眠死去，无法唤醒。但是没有细究原因。这个EFI睡眠是没有问题的
