### ISSUE TITLE
请问你的网卡工作吗

### ISSUE THREAD

**Issue by XiaojunXie** [L0ngxhn/hackintosh-GIGABYTE-Z390-GAMING-X#4]
我也是z390 gaming x，自从升到Monterey以后网卡就不工作了
然后wifi也是时不时抽风，正常是100mb/s，但是经常会变成只有6-7mb/s，需要重启才能解决

**Comment by L0ngxhn** [comment]
网卡正常工作，未发现问题。 如果有线网卡出现问题，请回退网卡驱动
