### ISSUE TITLE
蓝牙问题咨询

### ISSUE THREAD

**Issue by leixjin** [L0ngxhn/hackintosh-GIGABYTE-Z390-GAMING-X#7]
你好，升级到 Monterey 12.6.1 之后，蓝牙正常，睡眠正常，但在睡眠唤醒之后，蓝牙进程 bluetoothd 一直保持高 CPU 占用，开关蓝牙一次才能恢复正常，这个有办法解决吗？

**Comment by L0ngxhn** [comment]
请详细说一下wifi和蓝牙设备型号，目前我在用13系统

**Comment by L0ngxhn** [comment]
因为我用的wifi和蓝牙是拆机免驱，所以不存在这种问题。如果你使用的intel的,我也没法给出解决方案~

**Comment by leixjin** [comment]
已解决～
