### ISSUE TITLE
升级到最新版本系统，不能双硬解了

### ISSUE THREAD

**Issue by chahualao** [L0ngxhn/hackintosh-GIGABYTE-Z390-GAMING-X#9]

**Comment by L0ngxhn** [comment]
考虑显卡和机型问题？目前假期 未使用该黑苹果机器

**Comment by L0ngxhn** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/32266589/217443446-81a60ad4-26a2-4bcd-b875-2b38510cd6f7.png"> 5700xt显卡目前正常
